"use client";

import { useGetBoqReportPreviewQuery } from "@/store/api/projectsApi";
import { ReportToolbar } from "./ReportToolbar";
import { ReportHeader } from "./ReportHeader";
import { ExecutiveSummary } from "./ExecutiveSummary";
import { BOQTable } from "./BOQTable";
import { TermsAndNotes } from "./TermsAndNotes";
import { Skeleton } from "@/components/ui/skeleton";
import { BoqReportPreview } from "@/types/projects";
import {
  BOQReport,
  BOQSection,
  CostCategory,
  ResourceAllocation,
} from "./types";

interface BOQReportViewProps {
  projectId: string;
  basePath?: string; // e.g. "/projects" or "/enterprise/projects"
}

export function BOQReportView({
  projectId,
  basePath = "/projects",
}: BOQReportViewProps) {
  const {
    data: apiResponse,
    isLoading,
    error,
  } = useGetBoqReportPreviewQuery(projectId);

  if (isLoading) {
    return <BOQReportLoadingState />;
  }

  if (error || !apiResponse?.success) {
    return (
      <div className="p-12 text-center">
        <h2 className="text-xl font-semibold text-red-600">
          Failed to load BOQ Preview
        </h2>
        <p className="text-muted-foreground mt-2">
          There was an error fetching the report data. Please try again later.
        </p>
      </div>
    );
  }

  const report = mapApiToUiReport(apiResponse.data);

  return (
    <div className="">
      {/* Non-printable toolbar */}
      <div className="print:hidden">
        <ReportToolbar
          projectId={projectId}
          basePath={basePath}
          reportRef={report.meta.ref}
        />
      </div>

      {/* Document Body — print-friendly */}
      <div className="space-y-6">
        <ReportHeader meta={report.meta} />

        <ExecutiveSummary
          costCategories={report.costCategories}
          resourceAllocations={report.resourceAllocations}
          grandTotal={report.grandTotal}
        />

        <BOQTable sections={report.sections} grandTotal={report.grandTotal} />

        <div className="pt-2">
          <TermsAndNotes terms={report.terms} />
        </div>

        {/* Print-only footer line */}
        <div className="hidden print:block text-center text-[10px] text-muted-foreground pt-6 border-t border-border">
          Generated by QuantifyPro AI · {report.meta.ref} ·{" "}
          {report.meta.dateGenerated}
        </div>
      </div>
    </div>
  );
}

function mapApiToUiReport(data: BoqReportPreview): BOQReport {
  const dateFormatted = new Date(data.generatedAt).toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });

  // Map Cost Categories
  const costCategories: CostCategory[] =
    data.executiveSummary.costDistribution.map((dist, idx) => {
      const colors = [
        "bg-amber-500",
        "bg-blue-500",
        "bg-emerald-500",
        "bg-purple-500",
        "bg-rose-500",
        "bg-slate-500",
      ];
      return {
        name: dist.sectionName,
        value: dist.amount,
        percentage: dist.percentage,
        color: colors[idx % colors.length],
      };
    });

  // Map Resource Allocations
  const res = data.executiveSummary.resourceAllocation;
  const resourceAllocations: ResourceAllocation[] = [
    { label: "Labour", percentage: res?.labour, color: "bg-blue-500" },
    { label: "Material", percentage: res?.material, color: "bg-emerald-500" },
    { label: "Machinery", percentage: res?.machinery, color: "bg-amber-500" },
  ];

  // Map Sections
  const sections: BOQSection[] = data.sections.map((sec, idx) => ({
    id: `sec-${idx}`,
    title: `${idx + 1}.0 - ${sec.sectionName}`,
    subtotal: sec.subtotal,
    items: sec.rows.map((row, rowIdx) => ({
      item: row.itemCode || `${idx + 1}.${idx + rowIdx}`,
      description: row.description,
      unit: row.unit || "-",
      qty: row.quantity || 0,
      rate: row.rate || 0,
      total: row.amount || 0,
    })),
  }));

  return {
    meta: {
      companyName: data.company?.name || "QuantifyPro Analysis",
      companySubtitle:
        data.company?.address || "Intelligent Quantity Surveying",
      dateGenerated: dateFormatted,
      ref: data.referenceNumber,
      location: data.project.projectLocation,
      reportTitle: data.project.name,
      reportSubtitle: data.project.description,
    },
    sections,
    costCategories,
    resourceAllocations,
    grandTotal: data.executiveSummary.grandTotal,
    terms: [data.termsAndNotes],
  };
}

function BOQReportLoadingState() {
  return (
    <div className="p-6 md:p-8 max-w-5xl mx-auto space-y-8 animate-pulse">
      <div className="flex justify-between items-start">
        <div className="space-y-3">
          <Skeleton className="h-8 w-64" />
          <Skeleton className="h-4 w-48" />
        </div>
        <Skeleton className="h-12 w-12 rounded-full" />
      </div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Skeleton className="h-32 rounded-xl" />
        <Skeleton className="h-32 rounded-xl" />
        <Skeleton className="h-32 rounded-xl" />
      </div>
      <Skeleton className="h-[400px] w-full rounded-xl" />
    </div>
  );
}
