"use client";

import { MOCK_BOQ_REPORT } from "./mock-data";
import { ReportToolbar } from "./ReportToolbar";
import { ReportHeader } from "./ReportHeader";
import { ExecutiveSummary } from "./ExecutiveSummary";
import { BOQTable } from "./BOQTable";
import { TermsAndNotes } from "./TermsAndNotes";

interface BOQReportViewProps {
  projectId: string;
  basePath?: string; // e.g. "/projects" or "/enterprise/projects"
}

export function BOQReportView({ projectId, basePath = "/projects" }: BOQReportViewProps) {
  // Future: fetch from API using projectId
  const report = MOCK_BOQ_REPORT;

  return (
    <div className="p-6 md:p-8 max-w-5xl mx-auto">
      {/* Non-printable toolbar */}
      <div className="print:hidden">
        <ReportToolbar
          projectId={projectId}
          basePath={basePath}
          reportRef={report.meta.ref}
        />
      </div>

      {/* Document Body — print-friendly */}
      <div className="space-y-6">
        <ReportHeader meta={report.meta} />

        <ExecutiveSummary
          costCategories={report.costCategories}
          resourceAllocations={report.resourceAllocations}
          grandTotal={report.grandTotal}
        />

        <BOQTable sections={report.sections} grandTotal={report.grandTotal} />

        <div className="pt-2">
          <TermsAndNotes terms={report.terms} />
        </div>

        {/* Print-only footer line */}
        <div className="hidden print:block text-center text-[10px] text-muted-foreground pt-6 border-t border-border">
          Generated by QuantifyPro AI · {report.meta.ref} · {report.meta.dateGenerated}
        </div>
      </div>
    </div>
  );
}
