"use client";

interface PrintFooterProps {
  reportRef: string;
  dateGenerated: string;
}

export function PrintFooter({ reportRef, dateGenerated }: PrintFooterProps) {
  return (
    <div className="hidden print:block text-center text-[10px] text-muted-foreground pt-6 border-t border-border">
      Generated by QuantifyPro AI · {reportRef} · {dateGenerated}
    </div>
  );
}
