import type { BOQDocument, BOQItem } from "./types";

// TODO: replace with the real BOQ payload once the API shape is agreed.

const PREPARED_BY = "Cost Cliff Consultants";

function lump(ref: string, description: string, amount: number): BOQItem {
  return {
    id: `p-${ref}`,
    ref,
    description,
    qty: null,
    unit: null,
    rate: null,
    lumpSum: amount,
    measurementMethod: "Lump Sum",
    lastEditedAt: "11 Mar 2026",
    lastEditedBy: PREPARED_BY,
  };
}

function measured(
  id: string,
  ref: string,
  description: string,
  qty: number,
  unit: string,
  rate: number,
  measurementMethod = "Linear Metres (m)",
): BOQItem {
  return {
    id,
    ref,
    description,
    qty,
    unit,
    rate,
    measurementMethod,
    lastEditedAt: "11 Mar 2026",
    lastEditedBy: PREPARED_BY,
  };
}

const PRELIMINARY_ITEMS: BOQItem[] = [
  ["1.10", "Care for Existing Installations", 61_030_000],
  ["1.11", "Watching, Lighting and Protection", 4_041_758],
  ["1.12", "Surface and Spring Water Control", 2_133_528],
  ["1.13", "Site Board", 1_179_480],
  ["1.14", "Temporary Roads & Site Fences", 8_893_000],
  ["1.15", "Temporary Lighting and Power Distribution", 40_771_750],
  ["1.16", "Temporary Site Office & Personnel Shelter", 1_540_000],
  ["1.17", "Temporary Warehousing & Material Storage", 28_939_000],
  ["1.18", "First Aid Equipment & Medical Stations", 20_385_000],
  ["1.19", "Quality Control, Health, Safety & Environment (HSE)", 18_995_000],
  ["1.20", "Exterminate & Prevent Pests / Fumigations", 12_231_000],
  ["1.21", "Heavy Plant and Construction Equipment", 137_142_000],
  ["1.22", "Temporary Scaffolding, Shoring, Propping", 48_926_000],
  ["1.23", "Water Logistics for Concrete / Works", 43_924_000],
  ["1.24", "Engineering Setting Out", 16_300_000],
  ["1.25", "PPE — Personal Protective Equipment", 16_300_000],
  ["1.26", "Contractor's All Risk Insurance Cover", 24_462_000],
  ["1.27", "Advance Payment Bond Underwriting", 16_300_000],
  ["1.28", "Performance Bond Underwriting", 6_784_000],
  ["1.29", "Allowance for Architect Instructions", 4_077_000],
  ["1.30", "Progress Photographs, Scheduling & Reports", 12_231_000],
  ["1.31", "Samples and Material Quality Labs Testing", 28_539_000],
  ["1.32", "Site Rubbish Removal & Final Debris Disposal", 16_300_000],
  ["1.33", "Technical Management and Supervision", 28_923_000],
  ["1.34", "Post-Build Testing and Plant Commissioning", 22_631_200],
  ["1.35", "Site Governance Meetings & Catering", 16_328_000],
].map(([ref, description, amount]) =>
  lump(ref as string, description as string, amount as number),
);

export const DUMMY_BOQ_DOCUMENT: BOQDocument = {
  title: "Bill of Quantities — PROPOSED RESIDENTIAL DEVELOPMENT",
  subtitle:
    "No. 143a, Taslim Elias Close, Off Ahmadu-Bello Way, Victoria Island, Lagos",

  projectInfo: {
    client: "Mr. Adeyemi Oluwadamilare Abraham",
    location: "143a Taslim Elias Close, Victoria Island, Lagos",
    preparedBy: "Cost Cliff Consultants Ltd",
    date: "11 March 2026",
  },

  bills: [
    {
      id: "bill-1",
      code: "BILL NO. 1",
      title: "PRELIMINARIES & GENERAL ITEMS",
      pageLabel: "Pages 6-8",
      subsections: [
        {
          id: "sub-1-1",
          code: "1-1",
          title: "CONTRACTOR GENERAL OBLIGATIONS",
          accent: "amber",
          columns: "amount-only",
          items: PRELIMINARY_ITEMS,
        },
      ],
    },

    {
      id: "bill-2a",
      code: "BILL NO. 2-A",
      title: "PILING MAIN BUILDING WORKS",
      pageLabel: "Pages 8-9",
      subsections: [
        {
          id: "sub-2a",
          code: "2A",
          title: "PILING & GROUND INVESTIGATION",
          accent: "amber",
          columns: "full",
          items: [
            measured(
              "2a-a",
              "A",
              "Confirmatory Soil Profiles: 3 penetrometer tests + 1 borehole to 25m depth, lab evaluation & 5 report transcripts",
              1,
              "LS",
              3_000_000,
              "Lump Sum",
            ),
            measured(
              "2a-b",
              "B",
              "Specialised Bonds & Dilapidation Appraisals for Piling Phase",
              1,
              "LS",
              40_000_000,
              "Lump Sum",
            ),
            measured(
              "2a-c",
              "C",
              "Heavy Piling Rig Deployment / De-mobilisation (transit both ways)",
              1,
              "LS",
              10_000_000,
              "Lump Sum",
            ),
            measured(
              "2a-d",
              "D",
              "Survey Points & Rig Placement: 124 geometric layouts + track alignment",
              1,
              "LS",
              2_157_600,
              "Lump Sum",
            ),
            measured(
              "2a-e",
              "E",
              "CFA Boring: 800mm dia. to 35m depth, SWL 2700kN, Grade 30 cage layouts",
              4_340,
              "m",
              81_600,
              "Linear Metres (m)",
            ),
            measured(
              "2a-f",
              "F",
              "In-Situ CFA Piling Cast (Grade 20 Concrete)",
              2_110,
              "cu.m",
              269_517.52,
              "Cubic Metres (cu.m)",
            ),
            measured(
              "2a-g",
              "G",
              "Earth Spoil Clearing: extraction & carriage of drilling displacement",
              2_110,
              "cu.m",
              12_000,
              "Cubic Metres (cu.m)",
            ),
            measured(
              "2a-h",
              "H",
              "Compression Pile & Integrity Evaluation (PIT): 124 nodes",
              124,
              "nr",
              143_314.52,
              "Number (nr)",
            ),
          ],
        },
      ],
    },

    {
      id: "bill-2b",
      code: "BILL NO. 2-B",
      title: "SUBSTRUCTURE WORKS",
      pageLabel: "Pages 10-13",
      subsections: [
        {
          id: "sub-2b-e",
          code: "2B-E",
          title: "EARTHWORKS & EXCAVATION",
          accent: "blue",
          columns: "full",
          items: [
            lump("D20", "Excavation: Ground Beam foundations (up to 1m depth)", 216_736),
            measured(
              "2be-d21",
              "D21",
              "Excavation: Pile Caps (1.0m to 3.0m depth)",
              1_852,
              "cu.m",
              4_200,
              "Cubic Metres (cu.m)",
            ),
            lump("G1", "Working space / shoring: Ground Beams", 11_887_309),
            measured(
              "2be-g2",
              "G2",
              "Working space / shoring: Pile Caps",
              773,
              "cu.m",
              15_600,
              "Cubic Metres (cu.m)",
            ),
            measured(
              "2be-f",
              "F",
              "Imported fill: raise structural platform levels",
              682,
              "cu.m",
              26_280,
              "Cubic Metres (cu.m)",
            ),
            measured(
              "2be-k",
              "K",
              "Disposal of spoil off-site",
              1_903,
              "cu.m",
              7_800,
              "Cubic Metres (cu.m)",
            ),
            measured(
              "2be-l",
              "L",
              "Dewatering: provisional lump-sum allocation",
              1,
              "LS",
              20_000_000,
              "Lump Sum",
            ),
            measured(
              "2be-m",
              "M",
              "Anti-termite treatment (Dieldrex application on soil beds)",
              600.9,
              "sq.m",
              1_800,
              "Square Metres (sq.m)",
            ),
          ],
        },
        {
          id: "sub-2b-c",
          code: "2B-C",
          title: "CONCRETE ELEMENTS",
          accent: "blue",
          columns: "full",
          items: [
            measured(
              "2bc-a",
              "A",
              "Head trimming: 124 piles (1000mm dia. × 3000mm), integrate rebar with foundation",
              124,
              "nr",
              54_000,
              "Number (nr)",
            ),
            lump("B", "Blinding Layer: Grade 15 concrete under beams, caps & slabs", 15_353_419),
            measured(
              "2bc-c",
              "C",
              "Reinforced Pile Caps (Grade 25 Concrete)",
              1_401,
              "cu.m",
              204_982.44,
              "Cubic Metres (cu.m)",
            ),
            measured(
              "2bc-d",
              "D",
              "Reinforced Ground Beams (Grade 25 Concrete)",
              125,
              "cu.m",
              204_982.44,
              "Cubic Metres (cu.m)",
            ),
            measured(
              "2bc-e",
              "E",
              "Ground Beds and Lift Slab Footings (150–450mm thick)",
              181,
              "cu.m",
              204_982.44,
              "Cubic Metres (cu.m)",
            ),
          ],
        },
        {
          id: "sub-2b-r",
          code: "2B-R",
          title: "REINFORCEMENT & FORMWORK",
          accent: "blue",
          columns: "full",
          items: [
            measured(
              "2br-r",
              "R",
              "High-Yield Rebar (12–25mm dia.): pile caps, beams, lift shaft, foundation column rods @460N/mm²",
              168.94,
              "ton",
              1_746_000,
              "Tonnes (ton)",
            ),
            measured(
              "2br-f1",
              "F1",
              "Sawn formwork: Ground beam perimeter faces",
              1_083,
              "sq.m",
              21_600,
              "Square Metres (sq.m)",
            ),
            measured(
              "2br-f2",
              "F2",
              "Sawn formwork: Pile cap shuttering faces (height > 3m)",
              976,
              "sq.m",
              21_600,
              "Square Metres (sq.m)",
            ),
          ],
        },
      ],
    },

    {
      id: "bill-2c",
      code: "BILL NO. 2-C",
      title: "REINFORCED CARCASS STRUCTURAL FRAME",
      pageLabel: "Page 14",
      subsections: [
        {
          id: "sub-2c",
          code: "2C",
          title: "STRUCTURAL FRAME: CONCRETE, REBAR & FORMWORK",
          accent: "green",
          columns: "full",
          items: [
            measured("2c-a", "A", "Vertical Columns — Grade 30 structural mix", 764.41, "cu.m", 222_671.28, "Cubic Metres (cu.m)"),
            measured("2c-b", "B", "Reinforced Lift Core Walls — Grade 25 mix", 405, "cu.m", 204_982.44, "Cubic Metres (cu.m)"),
            measured("2c-d", "D", "Structural Beams (attached & isolated layouts) — Grade 25", 2_294, "cu.m", 204_982.44, "Cubic Metres (cu.m)"),
            measured("2c-e", "E", "Swimming Pool Tank Structure — Grade 30, waterproof compound mix", 32, "cu.m", 237_071.28, "Cubic Metres (cu.m)"),
            measured("2c-r1", "R1", "Column rebar (460N/mm²)", 148.29, "ton", 1_746_000, "Tonnes (ton)"),
            measured("2c-r2", "R2", "Beam structural rebar (460N/mm²)", 299.36, "ton", 1_746_000, "Tonnes (ton)"),
            measured("2c-r3", "R3", "Lift shaft rebar setups (460N/mm²)", 42.5, "ton", 1_746_000, "Tonnes (ton)"),
            measured("2c-f1", "F1", "Formwork: suspended beam soffits (3.0m–4.5m height range)", 17_316, "sq.m", 21_600, "Square Metres (sq.m)"),
            measured("2c-f2", "F2", "Formwork: square / rectangular column panels", 4_024, "sq.m", 21_600, "Square Metres (sq.m)"),
            measured("2c-f3", "F3", "Formwork: circular architectural column elements", 59, "sq.m", 29_000, "Square Metres (sq.m)"),
          ],
        },
      ],
    },

    {
      id: "bill-me",
      code: "SPECIALISED MECHANICAL, ELECTRICAL & FINISHING SYSTEMS",
      title: "",
      pageLabel: "",
      subsections: [
        {
          id: "sub-me",
          code: "M&E",
          title: "PLUMBING, HVAC, FIRE, ELECTRICAL & LOW-VOLTAGE INFRASTRUCTURE",
          accent: "orange",
          columns: "amount-only",
          items: [
            lump("M", "Plumbing & Mechanical: HVAC cassettes, fire pump, dry riser, pressurised water reservoirs, extract arrays", 5_478_844_718),
            lump("E", "Electrical & LV: containment, cable trays, emergency lighting, PA systems, lightning grounding", 4_061_345_797),
            lump("W", "Liquid Applied Tanking Waterproofing: 4mm Mariseal 250 PU coating (101 sq.m @ ₦27,360)", 2_760_474),
            lump("D1", "Security Entrance: Type D1 laminated single-swing door (4.51m × 2.939m)", 9_941_168),
            lump("D3", "Security Entrance: Type D3 door (1.5m × 2.1m)", 2_362_500),
            lump("C1", "Ceiling: Main POP suspended screeding work (8,209 sq.m @ ₦18,000)", 147_760_194),
            lump("C2", "Ceiling: Longspan aluminium grilling 125×35×6mm (839 sq.m @ ₦132,000)", 110_750_597),
          ],
        },
      ],
    },
  ],

  summaryRows: [
    { billNo: "1", description: "Preliminaries Breakdown Total", billId: "bill-1" },
    { billNo: "2-A", description: "Piling Main Building Works", billId: "bill-2a" },
    { billNo: "2-B", description: "Substructure Works", billId: "bill-2b" },
    { billNo: "2-C", description: "Carcass Frame Works", billId: "bill-2c" },
    { billNo: "2-D", description: "Upper Floors Architecture", amount: 1_175_460_297.45 },
    { billNo: "2-E", description: "Roof Structures", amount: 20_516_562.31 },
    { billNo: "2-F", description: "Staircases Construction", amount: 52_692_000 },
    { billNo: "2-G", description: "External Walls", amount: 34_080_086 },
    { billNo: "2-H", description: "Internal Walls", amount: 285_242_696 },
    { billNo: "2-I", description: "Windows & Doors", amount: 2_680_856_168 },
    { billNo: "2-J", description: "Internal Doors", amount: 342_916_148 },
    { billNo: "2-K", description: "Plumbing & Mechanical", amount: 5_478_844_718.15 },
    { billNo: "2-L", description: "Electrical", amount: 4_061_345_797.16 },
    { billNo: "2-M", description: "Floor Finishes", amount: 456_122_039 },
    { billNo: "2-N", description: "Wall Finishes", amount: 822_075_045 },
    { billNo: "2-O", description: "Ceiling Finishes", amount: 358_738_938.85 },
    { billNo: "2-P", description: "Fittings", amount: 597_250_000 },
  ],

  externalWorks: 0,
  contingencyRate: 0.05,
  vatRate: 0.075,
  preliminariesBillNo: "1",

  meta: {
    lastEdited: "Today 10:32 AM",
    version: "2.4",
    ref: "RC 1759200",
    firm: "Cost Cliff Consultants Limited",
  },
};
